name: 'growth_accounting'
version: '1.0.0'
config-version: 2

profile: 'growth_accounting'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  growth_accounting:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: marts

    metrics:
      +materialized: table
      +schema: metrics